# -*- coding: utf-8 -*-
"""env.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMOKTnyVCk-5zVMtXVE3G5vOYeWQNQvW
"""

import streamlit as st
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, BaggingRegressor
import pickle

# Load the dataset
df = pd.read_csv('car_details.csv')

# Sidebar for user input
st.sidebar.header("Car Details Input")

# Input fields for user to enter car details
year = st.sidebar.slider("Year", int(df['year'].min()), int(df['year'].max()), int(df['year'].mean()))
km_driven = st.sidebar.number_input("Kilometers Driven", min_value=0, value=int(df['km_driven'].mean()))
fuel = st.sidebar.selectbox("Fuel Type", df['fuel'].unique())
seller_type = st.sidebar.selectbox("Seller Type", df['seller_type'].unique())
transmission = st.sidebar.selectbox("Transmission", df['transmission'].unique())
owner = st.sidebar.selectbox("Owner", df['owner'].unique())

# Preprocess user input
user_input = pd.DataFrame({
    'year': [year],
    'km_driven': [km_driven],
    'fuel': [fuel],
    'seller_type': [seller_type],
    'transmission': [transmission],
    'owner': [owner]
})

# Encode categorical variables
le = LabelEncoder()
user_input['fuel'] = le.fit_transform(user_input['fuel'])
user_input['seller_type'] = le.fit_transform(user_input['seller_type'])
user_input['transmission'] = le.fit_transform(user_input['transmission'])
user_input['owner'] = le.fit_transform(user_input['owner'])

# Separate features (X) and target variable (y)
X = df.drop(['selling_price', 'name'], axis=1)

# Encode categorical features in the main dataframe
X['fuel'] = le.fit_transform(X['fuel']) # Encode 'fuel' column in the main dataframe
X['seller_type'] = le.fit_transform(X['seller_type'])
X['transmission'] = le.fit_transform(X['transmission'])
X['owner'] = le.fit_transform(X['owner'])
X = pd.get_dummies(X, columns=['transmission'])

y = df['selling_price']


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Linear Regression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_predictions = lr_model.predict(X_test)
lr_mse = mean_squared_error(y_test, lr_predictions)
lr_r2 = r2_score(y_test, lr_predictions)
print(f"Linear Regression - MSE: {lr_mse}, R-squared: {lr_r2}")

# Random Forest Regression
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)
rf_mse = mean_squared_error(y_test, rf_predictions)
rf_r2 = r2_score(y_test, rf_predictions)
print(f"Random Forest Regression - MSE: {rf_mse}, R-squared: {rf_r2}")

# Gradient Boosting Regression
gb_model = GradientBoostingRegressor(random_state=42)
gb_model.fit(X_train, y_train)
gb_predictions = gb_model.predict(X_test)
gb_mse = mean_squared_error(y_test, gb_predictions)
gb_r2 = r2_score(y_test, gb_predictions)
print(f"Gradient Boosting Regression - MSE: {gb_mse}, R-squared: {gb_r2}")

# Bagging Regression
bagging_model = BaggingRegressor(random_state=42)
bagging_model.fit(X_train, y_train)
bagging_predictions = bagging_model.predict(X_test)
bagging_mse = mean_squared_error(y_test, bagging_predictions)
bagging_r2 = r2_score(y_test, bagging_predictions)
print(f"Bagging Regression - MSE: {bagging_mse}, R-squared: {bagging_r2}")


# Save the best model (e.g., Random Forest)
best_model = rf_model  # Replace with the actual best model
filename = 'best_model.sav'
pickle.dump(best_model, open(filename, 'wb'))
# Load the saved model
loaded_model = pickle.load(open('best_model.sav', 'rb'))

# Make prediction
if st.sidebar.button("Predict Selling Price"):
    prediction = loaded_model.predict(user_input)
    st.write(f"Predicted Selling Price: {prediction[0]}")

# Display the dataset
st.title("Car Details Dataset")
st.write(df.head())

# Display the correlation matrix
st.title("Correlation Matrix")
numerical_df = df.select_dtypes(include=['number'])
st.write(numerical_df.corr())

# Display the histograms
st.title("Histograms")

st.write("Distribution of Car Year")
fig, ax = plt.subplots()
ax.hist(df['year'])
st.pyplot(fig)

st.write("Distribution of Selling Price")
fig, ax = plt.subplots()
ax.hist(df['selling_price'])
st.pyplot(fig)

st.write("Distribution of Kilometers Driven")
fig, ax = plt.subplots()
ax.hist(df['km_driven'])
st.pyplot(fig)

# Display the scatter plot
st.title("Scatter Plot")
plt.figure(figsize=(8, 6))
sns.scatterplot(x='year', y='selling_price', data=df)
plt.title('Year vs Selling Price')
st.pyplot(plt)

# Display the pairplot
st.title("Pairplot")
sns.pairplot(df[['selling_price', 'km_driven', 'year']])
st.pyplot(plt)